[project]
name = "fasthtml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "img2pdf>=0.6.1",
    "ipykernel>=7.0.1",
    "pillow>=12.0.0",
    "python-fasthtml>=0.12.30",
    "requests>=2.32.5",
]
